---
- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: restart supervisor
  service:
    name: supervisor   # Ubuntu usa 'supervisor', não 'supervisord'
    state: restarted
